friendica/friendica-addons

windowsphonepush/windowsphonepush.php
add functionality to highlight new entries in Windows Phone app, bugfix
on sql for counter (likes/dislikes now excluded)
=> windowsphonepush Version 2.0

securemail/securemail.php
send encrpyted mail only as text
=> securemail: null html body

impressum/impressum.php
During the hunt for unproxied pictures I saw that this has to be done in the impressum as well.
=> If there were pictures in the impressum then they would be proxied as well

twitter/twitter.php
=> Made the help text more precise

ldapauth/ldapauth.php
* clean code format
* fix part of code ```$b['user_record'] = $results[0];```
* fix resolving ```$emailarray``` and ```$namearray``` if only ```$ldap_autocreateaccount == "true"```
=> Clean code and fix potential issues

fromgplus/fromgplus.php, pumpio/pumpio.php, twitter/twitter.php
There is a new function in the core for the "share" header. This is now supported (with background compatibility)
=> Support for new "share_header" function

fbpost/fbpost.php
There were cases where the mirror function hasn't fetched posts.
=> fbpost: The privacy check is improved again.

appnet/appnet.php, pumpio/pumpio.php, statusnet/statusnet.php, twitter/twitter.php
This is needed for the new condensed notifications.
=> The "id" field is now filled in the notifications

openstreetmap/openstreetmap.js, openstreetmap/openstreetmap.php, openstreetmap/templates/admin.tpl
Port of openstreetmap plugin from Red.
Supports hooks for [map] bbcode
=> Openstreetmap v.1.3

statusnet/statusnet.php
Users can now decide if they want to import the whole timeline or only the posts where they were mentioned. This should help in migrating from a Statusnet/GNU Social account to using Friendica for OStatus.
=> New option to fetch only mentions.

googlemaps/googlemaps.php, openstreetmap/openstreetmap.php
There is a new addon that uses Google Maps for card services. Additionally the link to the maps in the OSM addon is changed to a simpler format. (There is no need to name a link "map" when there is an appropriate link name)
=> New addon GoogleMaps, changed map format for OSM

planets/planets.php
I added the HTML code for the "minimized" settings header that was missing when I copied this plugin to use as a base for the krynn plugin. 
All the HTML is added along with closing the second <div> on line 162
=> Add HTML code to planets.php as requested to match spec

snautofollow/snautofollow.php
This pull request should be accepted, once the pull request https://github.com/friendica/friendica/pull/1756 is accepted.
=> snautofollow is deprecated since it moved into the core

krynn/krynn.php
Fixed reported grammar error for a location.
Tested on theronin.net and working correctly.
=> Fixed reported grammar error for a location

statistics_json/statistics_json.php
The functionality moved into the core.
=> The statistics addon is now deprecated

langfilter/langfilter.php
it's very unlikely that you don't speak your own language...
=> Do not filter out own messages

langfilter/langfilter.php
so the language detection is centralized
PS: could be done better, like checking percentage and also accept if unsure.
=> Use system detected language

curweather/curweather.php
Reducing the cache storage time of "curweather" to one hour.
=> Hourly cache for the curweather addon

leistungsschutzrecht/leistungsschutzrecht.php
The addon now shows the title and the first seven words of the text.
=> Adopt it to the new proposals for the agreement between Google and VG Media

irc/irc.php
This should fix https://github.com/friendica/friendica/issues/1993
=> magic of a dot

buffer/lang/it/messages.po, buffer/lang/it/strings.php
strk updated the IT translation of the buffer addon on transifex. THx!
=> IT: update to the buffer translation

pumpio/oauth/oauth_client.php, pumpio/pumpio.php
Pump.io servers crash in a very bad way that prevents the requests to be finished.
There is now a check for this.
=> Pumpio: Improved Timeout check

statusnet/statusnet.php
I guess I finally found the reason why my avatar picture got worse day by day and why sometimes my username changed.
=> Bugfix: The Statusnet connector destroyed the avatar and the name

appnet/appnet.php, buffer/buffer.php, statusnet/statusnet.php, twitter/twitter.php
The function "plaintext" was enhanced for the OStatus export. For this reason we need to make small changes to the connectors.
=> Needed changes for a changed core function

nsfw/nsfw.php
Changed the input field in settings to a textarea to make it more comfortable with longer lists
=> Nsfw input

mailstream/mailstream.php, mailstream/templates/settings.tpl
Provides some more configuration options and includes various bugfixes.  I've now been using this long enough that I'm willing to call it "1.0".
=> Mailstream version 1.0

appnet/appnet.php, pumpio/pumpio.php, statusnet/statusnet.php, twitter/twitter.php
In the develop branch there is now a different functionality for notifications. This pull request adopts the changes to the addons as well. (But will work with the master branch as well)
=> App.net/Pump.io/GNU Social/Twitter: Support for new notifications

fromgplus/fromgplus.php
Location data is now transmitted in the posts.
=> Fromgplus: Add location and coordinates to posts

pumpio/pumpio.php
Posted videos to pump.io look better when we don't try to "enhance" them.
=> Pump.io: Posted videos look better now

wppost/wppost.php
The old title detection used the bookmark element - now it uses a centralized function.
=> wppost: Better title detection

appnet/appnet.php, pumpio/pumpio.php, statusnet/statusnet.php, twitter/twitter.php
There were issues with avatar pictures in comments that weren't stored in the contacts with uid=0 and the gcontacts.
=> Pumpio now has a better contact management

twitter/twitter.php
This should prevent the system from posting the same stuff over and over again.
=> Twitter: Prevent posting loops

notifyall/notifyall.php
for friendica/friendica#2764
* in test mode send the notification mail only to the admin(s) of the node
* use the system set sender email or `noreply`
this also might need reflection in friendica/friendica#2768 so this needs to be decided before the other PR is merged.
=> notifyall in test mode

krynn/lang/es/messages.po, krynn/lang/es/strings.php, langfilter/lang/es/messages.po, langfilter/lang/es/strings.php, tictac/lang/es/messages.po, tictac/lang/es/strings.php, uhremotestorage/lang/es/messages.po, uhremotestorage/lang/es/strings.php, windowsphonepush/lang/es/messages.po, windowsphonepush/lang/es/strings.php, wppost/lang/es/messages.po, wppost/lang/es/strings.php, yourls/lang/es/messages.po, yourls/lang/es/strings.php
with this the ES translation is at 100% again, thanks a lot to Albert and the other Spanish translation team members!
=> ES translation work - muchas gracias Albert

twitter/twitter.php
Currently this is done only when importing the timeline. The mirroring of posts has to be changed and the posting as well. But this can be done in a separate pull request.
=> Twitter: We now support quotes and long posts

twitter/twitter.php
Mirrored posts are now created with the same function like the timeline import. Videos are now embedded from Twitter.
=> Twitter: Videos are embedded, mirrored posts are improved

pumpio/pumpio.php
The new queries are now using the indexes better.
=> Pumpio: Optimised queries

appnet/appnet.php, buffer/buffer.php, pumpio/pumpio.php, pumpio/pumpio_sync.php, statusnet/statusnet.php, twitter/twitter.php, twitter/twitter_sync.php
This pull request removes some old stuff (for several versions we now have the "update_gcontact" function) and it is a preparation for upcoming pull requests to the 3.5.2 where some more functions will be removed.
Additionally the app.net addon is deprecated since the network will close in the next days.
=> Deprecated parts removed

superblock/lang/C/messages.po, superblock/superblock.php
Superblock had so far no collapsing setting headers. Also regenerated the messages.po file as the title of the settings changed.
=> Superblock

appnet/appnet.php, buffer/buffer.php, buffer/bufferapp.php, diaspora/diaspora.php, facebook/facebook.php, fbpost/fbpost.php, fbsync/fbsync.php, fromgplus/fromgplus.php, geocoordinates/geocoordinates.php, gpluspost/gpluspost.php, ifttt/ifttt.php, jappixmini/jappixmini.php, leistungsschutzrecht/leistungsschutzrecht.php, pumpio/pumpio.php, pumpio/pumpio_sync.php, rendertime/rendertime.php, statistics_json/statistics_json.php, statusnet/statusnet.php, tumblr/tumblr.php, twitter/twitter.php, twitter/twitter_sync.php, wppost/wppost.php, xmpp/xmpp.php
Addon version of https://github.com/friendica/friendica/pull/3528
=> Replace explicit php logical operators

leistungsschutzrecht/leistungsschutzrecht.php, retriever/README, retriever/retriever.php
See issue https://github.com/friendica/friendica/issues/3482
Accidentally this PR includes some other coding that I made some time ago but had never done a PR for this.
This other PR simply is a whitelist for a blacklist ;-)
=> Retriever is deactivated, see issue 3482

pumpio/pumpio.php
See issue https://github.com/friendica/friendica/issues/3636
=> Issue 3636: Avoid warning messages

unicode_smilies/unicode_smilies.php
Attention: This addon will work when the PR https://github.com/friendica/friendica/pull/3640 is merged. It won't do any harm if accepted even with the master branch - only thing is: It mustn't be activated on that branch.
=> New addon for Unicode emojis

extcron/extcron.php, poormancron/poormancron.php, procrunner/procrunner.php, unicode_smilies/unicode_smilies.php
We don't need any of them anymore.
=> All external poller addons are now deactivated

appnet/appnet.php, blogger/blogger.php, buffer/buffer.php, diaspora/diaspora.php, libertree/libertree.php, pumpio/pumpio.php, statusnet/statusnet.php, tumblr/tumblr.php, twitter/twitter.php, unicode_smilies/unicode_smilies.php, wppost/wppost.php
This works in conjunction with the pull request https://github.com/friendica/friendica/pull/3686
=> "remote self" should work now with the addons

unicode_smilies/unicode_smilies.php
See issue https://github.com/friendica/friendica/issues/3699
=> Unicode smilies: No tea anymore with tearsofjou

langfilter/langfilter.php
This PR should ony be approved after this one: https://github.com/friendica/friendica/pull/3743
=> Remove reference to library/langdet folder

langfilter/langfilter.php
Reverts friendica/friendica-addons#428
=> Revert "Remove reference to library/langdet folder"

newmemberwidget/newmemberwidget.php
I've changed the path of the global support forum to https://forum.friendi.ca/profile/helpers.
=> Update newmemberwidget with new global support forum

dav/friendica/database-init.inc.php, pumpio/pumpio_sync.php, twitter/twitter_sync.php
Just some small changes to make the addons compatible to the current develop. (But it will work in master as well)
=> Additional work for PR 3778

dav/README.md, dav/dav.php
In the current state @hoergen mentioned it is not really useable throwing many errors and needs someone to care about it.
=> DAV addon marked unsupported

langfilter/langfilter.php
This is a redux of #428, see https://github.com/friendica/friendica/pull/3871
=> Move languagedetect to vendor

nsfw/README
Added some uses cases and regex examples to the NSFW plugin's README.
=> NSFW examples

twitter/twitter.php
followup for  friendica/friendica#3873
=> del_pconfig -> PConfig::delete

diaspora/diaspora.php, mailstream/mailstream.php, nsfw/README, twitter/twitter.php
changes related to https://github.com/friendica/friendica/issues/3878
=> Class file relocation

curweather/curweather.php, geocoordinates/geocoordinates.php, googlemaps/googlemaps.php, openstreetmap/openstreetmap.php
Cache class moved to Friendica\Core namespace
Related to https://github.com/friendica/friendica/issues/3878
=> Move Cache to src

unicode_smilies/unicode_smilies.php
Smilies moved to Friendica\Content namespace.
Related to https://github.com/friendica/friendica/issues/3878
=> Smilies moved to src

pumpio/pumpio.php, statusnet/statusnet.php, twitter/twitter.php
Update references to socgraph to GContact namespace functions. Related to https://github.com/friendica/friendica/issues/3878
Related to https://github.com/friendica/friendica/pull/3903
=> GContact moved to src

curweather/templates/widget.tpl
The Show on map link was not working properly.
This could also be changed to open in a new Tab, but I know there is discussion about navigation control in the hands of the user... so I left that as is.
=> OpenWeatherMap

public_server/public_server.php, pumpio/pumpio.php, testdrive/testdrive.php
Relevant to https://github.com/friendica/friendica/issues/3878
- Add relevant use statements
- Change method calls
- Remove mentions to include/Contact.php
=> Move Contact to src

dav/friendica/main.php, notifyall/notifyall.php, securemail/securemail.php
See here: https://forum.friendi.ca/display/0b6b25a8125a15ef04e7a56291346959
=> Addons hadn't been changed for the moved emailer class

ifttt/ifttt.php, xmpp/xmpp.php
Related to https://github.com/friendica/friendica/issues/3946
This PR is independent of the above one, it only consists of formatting and simplified method calls.
A few translation strings have been changed though.
=> Use random bytes

ifttt/lang/C/messages.po, xmpp/lang/C/messages.po
=> added messages.po files to IFTTT and XMPP addons

fromgplus/fromgplus.php, pumpio/pumpio.php, statusnet/statusnet.php, twitter/twitter.php
updates for Photo class moving to Friendica\Object namespace.
Related to: https://github.com/friendica/friendica/issues/3878
=> Photo to namespace

dav/friendica/dav_friendica_auth.inc.php, jappixmini/jappixmini.php, windowsphonepush/windowsphonepush.php
Follow-up to https://github.com/friendica/friendica/pull/3970
Part of https://github.com/friendica/friendica/issues/3942
This PR fixes the formatting of 3 addons and replaces the hash function with the proper `User::authenticate` function.
=> Use User::authenticate

ldapauth/ldapauth.php
Addon pendant of https://github.com/friendica/friendica/pull/4003
Related to https://github.com/friendica/friendica/issues/3942
=> Move include/user to src

fromapp/fromapp.php, notimeline/notimeline.php, numfriends/numfriends.php, qcomment/qcomment.php
update false to is_null where needed.
related to https://github.com/friendica/friendica/issues/4020
=> Update false evaluations

fromgplus/fromgplus.php, pumpio/pumpio.php, statusnet/statusnet.php, twitter/twitter.php
Related to https://github.com/friendica/friendica/pull/4031
And related to https://github.com/friendica/friendica/issues/3878
=> Move objects to src

fromgplus/fromgplus.php, pumpio/pumpio.php, statusnet/statusnet.php, twitter/twitter.php
Reverts friendica/friendica-addons#468
=> Revert "Move objects to src"

fromgplus/fromgplus.php, pumpio/pumpio.php, statusnet/statusnet.php, twitter/twitter.php
Redux of #468 after main PR was fixed.
=> Revert "Revert "Move objects to src""

notifyall/lang/fr/messages.po, notifyall/lang/fr/strings.php, numfriends/lang/fr/messages.po, numfriends/lang/fr/strings.php
French translation for notifyall addon added and numfriends translation updated.
=> FR translation uppdate - thx Thecross

pumpio/pumpio.php, statusnet/statusnet.php, twitter/twitter.php
Related to https://github.com/friendica/friendica/issues/3878
Related to https://github.com/friendica/friendica/pull/4046
=> Move Group to src

pageheader/pageheader.css, pledgie/pledgie.css, yourls/yourls.css
=> Some small CSS fix

ldapauth/ldapauth.php
Follows https://github.com/friendica/friendica/pull/4054.
Related to https://github.com/friendica/friendica/issues/4041
=> Use Exceptions for User::create

ldapauth/ldapauth.php
Reverts friendica/friendica-addons#475
=> Revert "Use Exceptions for User::create"

ldapauth/ldapauth.php
Reverts friendica/friendica-addons#477
=> Revert "Revert "Use Exceptions for User::create""

pumpio/pumpio.php
Blocked by https://github.com/friendica/friendica/pull/4066
Follow-up to https://github.com/friendica/friendica/pull/4046
=> Remove group_member.uid in pumpio

langfilter/langfilter.php
Related to (but not blocked by) https://github.com/friendica/friendica/pull/4157
Nothing as scary, though, as I only have a handful of enabled plugins.
=> Fix PHP notice in langfilter

statusnet/statusnet.php, twitter/twitter.php
Blocked by https://github.com/friendica/friendica/pull/4156
=> Move oembed to src

communityhome/communityhome.php, dav/friendica/layout.fnk.php, dav/friendica/main.php, impressum/impressum.php, startpage/startpage.php, statusnet/statusnet.php, twitter/twitter.php
Blocked by https://github.com/friendica/friendica/pull/4092
=> Move auth to src

buffer/buffer.php, statusnet/statusnet.php, twitter/twitter.php
Blocked by #4166
- Remove unused argument in plaintext()
=> Fix unused code in buffer, statusnet and twitter

twitter/twitter.php
Related to (but not blocked by) #4172 
- Use template instead of manual HTML
=> Improve Twitter settings display

xmpp/xmpp.php
Belongs to https://github.com/friendica/friendica/pull/4180
=> Preparation to make the automatic authentication work (hopefully) reliable

buffer/buffer.php, diaspora/diaspora.php, ifttt/ifttt.php, libertree/libertree.php, pumpio/pumpio.php, statusnet/statusnet.php, tumblr/tumblr.php, twitter/twitter.php, windowsphonepush/windowsphonepush.php, wppost/wppost.php
Part of https://github.com/friendica/friendica/issues/4176
Blocked by https://github.com/friendica/friendica/pull/4194
=> Replace dba::select(limit => 1) by dba::selectFirst()

communityhome/communityhome.php, forumdirectory/forumdirectory.php
Blocked by https://github.com/friendica/friendica/pull/4253
=> Remove App::get_cached_avatar_image method

forumdirectory/forumdirectory.php
- Fix formatting
- Fix reference to nav_set_selected
- Fix reference to widget_findpeople
Reference: https://friendica.mrpetovan.com/display/adf174d5725a612b8a5f527654206258
=> Fix forumdirectory reference to deleted files/functions

forumdirectory/forumdirectory.php
See: https://forum.friendi.ca/display/adf174d5125a6335f1a0cb7251918461
=> Add missing include/fix zrl location to forumdirectory

smileybutton/smileybutton.php, windowsphonepush/windowsphonepush.php
=> Fix remaining call_hooks

diaspora/diaspora.php, pumpio/pumpio.php, twitter/twitter.php
remove references and update functions of removed queue_fn
=> Bug fix for Addons using queue_fn

buffer/buffer.php, statusnet/statusnet.php, tumblr/tumblr.php, twitter/twitter.php, wppost/wppost.php
Plaintext is now a class in src
Blocked by https://github.com/friendica/friendica/pull/4335
=> Plaintext moved to src

buffer/buffer.php, statusnet/statusnet.php, twitter/twitter.php
the shorten method moved to Plaintext class
=> Method moved to Plaintext

blogger/blogger.php, buffer/buffer.php, curweather/curweather.php, dwpost/dwpost.php, fortunate/fortunate.php, fromgplus/fromgplus.php, geocoordinates/geocoordinates.php, geonames/geonames.php, ijpost/ijpost.php, jappixmini/jappixmini.php, leistungsschutzrecht/leistungsschutzrecht.php, libertree/libertree.php, ljpost/ljpost.php, mailstream/mailstream.php, openstreetmap/openstreetmap.php, pumpio/pumpio.php, statusnet/statusnet.php, twitter/twitter.php, wppost/wppost.php
Related to https://github.com/friendica/friendica/issues/3878
Blocked by https://github.com/friendica/friendica/pull/4339
=> Network was moved to src

pumpio/pumpio.php, statusnet/statusnet.php, twitter/twitter.php
This PR is being blocked by https://github.com/friendica/friendica/pull/4351 and need to be merged at the same time.
=> New methods in item class

twitter/twitter.php
Fixes https://forum.friendi.ca/display/adf174d5805a6f178e00e4b316729072
=> Upgrade TwitterOAuth calls in twitter addon

statusnet/library/statusnetoauth.php, twitter/twitter.php
Follow-up to #510
Fixes https://github.com/friendica/friendica-addons/pull/511#issuecomment-361251587
Fixes https://friendica.mrpetovan.com/display/adf174d5235a6f3c4c048c4402249628
=> Follow-up TwitterOAuth fixes in StatusNet and Twitter addons

dav/common/calendar.fnk.php, dav/common/calendar_rendering.fnk.php, dav/common/wdcal_backend.inc.php, dav/common/wdcal_edit.inc.php, dav/friendica/dav_caldav_backend_virtual_friendica.inc.php, dwpost/dwpost.php, fromgplus/fromgplus.php, ijpost/ijpost.php, ljpost/ljpost.php, membersince/membersince.php, public_server/public_server.php, pumpio/pumpio.php, statusnet/statusnet.php, testdrive/testdrive.php, twitter/twitter.php
Blocked by https://github.com/friendica/friendica/pull/4327
=> Refactor datetime_convert() into DateTimeFormat::convert()

forumdirectory/forumdirectory.php
Part of https://github.com/friendica/friendica/issues/3878
Follow-up to #501
Blocked by https://github.com/friendica/friendica/pull/4387
=> Replace datetime functions by Temporal methods

dwpost/dwpost.php, ljpost/ljpost.php, membersince/membersince.php
`include/datetime.php` isn't available anymore in friendica core develop
=> remove include/datetime.php requirement

pumpio/pumpio.php, statusnet/statusnet.php, twitter/twitter.php
Has to be merged after https://github.com/friendica/friendica/pull/4404
=> Direct calls to the database are replaced by calls to the item class

tumblr/tumblr.php
Part of https://github.com/friendica/friendica/issues/3878
Blocked by https://github.com/friendica/friendica/pull/4399
=> Move include/bbcode to src/ part 1 : Everything but bbcode()

membersince/membersince.php
addresses https://github.com/friendica/friendica/issues/4412
=> membersince: fix utf-8 encoding issues

twitter/twitter.php
Fixes https://github.com/friendica/friendica/issues/4295
This is an extremely corner case that enabled me to fix a really weird behavior in the Twitter addon.
I'm too tired to explain tonight, if anyone is interested, hit me up in 12h.
=> [twitter] Fix mentions and urls mix up

twitter/twitter.php
Fixes https://github.com/friendica/friendica/issues/4409
=> [twitter] Add Exception handling/Fix OAuth usage

communityhome/communityhome.css
Quick fix for https://github.com/friendica/friendica/issues/4431
note:
This addon does need some more love to look good in frio.
=> communityhome: bring login button back in frio

blogger/blogger.php, diaspora/diaspora.php, dwpost/dwpost.php, ijpost/ijpost.php, impressum/impressum.php, libertree/libertree.php, ljpost/ljpost.php, mailstream/mailstream.php, newmemberwidget/newmemberwidget.php, notifyall/notifyall.php, pumpio/pumpio.php, statusnet/statusnet.php, tumblr/tumblr.php, windowsphonepush/windowsphonepush.php, wppost/wppost.php
Part of https://github.com/friendica/friendica/issues/3878
Follow-up to #516
Blocked by https://github.com/friendica/friendica/pull/4462
=> Move include/bbcode to src/ part 2: bbcode()

public_server/public_server.php
Possibly fixes https://github.com/friendica/friendica/issues/1312
The code is reworked and the user removal went to the "CronJobs" worker.
=> Reworked "public server" addon

diaspora/diaspora.php, libertree/libertree.php
Part of https://github.com/friendica/friendica/issues/3878
Blocked by https://github.com/friendica/friendica/pull/4548
=> [diaspora|libertree] Move bb2diaspora to BBCode::toMarkdown

communityhome/README.md, communityhome/communityhome.php, communityhome/templates/communityhome.tpl
Closes https://github.com/friendica/friendica/issues/4555
=> [communityhome] Remove active users feature

pumpio/pumpio.php, statusnet/statusnet.php, windowsphonepush/windowsphonepush.php, wppost/wppost.php
Depends on https://github.com/friendica/friendica/pull/4560
=> [develop] Move include/html2* to src/

pageheader/lang/C/messages.po, pageheader/pageheader.php, pageheader/templates/settings.tpl
additionally the messages.po was regenerated and the settings block moved to a template
=> [pageheader] bugfix: missing open/close of settings block

mailstream/lang/C/messages.po, mailstream/templates/settings.tpl
also the messages.po got regenerated
=> bugfix: mailstream addon was missing open/close settings header

nsfw/nsfw.php
It belongs to PR https://github.com/friendica/friendica/pull/4593
=> nsfw now ignores content warning posts and the code has been reformatted

INSTALL.txt
Part of https://github.com/friendica/friendica/issues/4629
Depends on https://github.com/friendica/friendica/pull/4630
=> Updated documentation about bin/composer

newmemberwidget/README.md
Part of https://github.com/friendica/friendica/issues/4629
Depends on https://github.com/friendica/friendica/pull/4628
=> Update documentation about po2php console command

langfilter/lang/nl/messages.po, langfilter/lang/nl/strings.php, xmpp/lang/nl/messages.po, xmpp/lang/nl/strings.php, yourls/lang/nl/messages.po, yourls/lang/nl/strings.php
The langfilter, xmpp and yourls addons got a NL translation thanks to Karel Vandecandelaere.
=> added some NL translations

nsfw/nsfw.php
Part of https://github.com/friendica/friendica/pull/4681
Depends on https://github.com/friendica/friendica/pull/4682
=> [nsfw] Add hashtag-only hiding

twitter/twitter.php
This avoids a crash of the worker task that wants to send the content to twitter.
=> Handle exception when posting pictures to twitter

twitter/twitter.php
This should make the posting of images more reliable.
=> Improved timeout values/Posting local files

rendertime/rendertime.php
=> Just a spelling mistake

catavatar/catavatar.php, catavatar/lang/C/messages.po
=> Cat Avatar Generator: Fix coding style

blockem/lang/de/messages.po, blockem/lang/de/strings.php, catavatar/lang/de/messages.po, catavatar/lang/de/strings.php, langfilter/lang/de/messagespo.po, langfilter/lang/de/strings.php, nsfw/lang/de/messages.po, nsfw/lang/de/strings.php, showmore/lang/de/messages.po, showmore/lang/de/strings.php
* Added catavatar translation
* updated translation of langfilter, blockem, nsfw, showmore
=> DE translation update

mathjax/mathjax.php, mathjax/templates/admin.tpl
* updated the MathJax CDN URL to the current one from their docs
* the variable name "baseurl" in the template caused a broken config form in the admin panel
=> fixing mathjax addon

catavatar/catavatar.php, catavatar/lang/C/messages.po
=> Catavatar: The profile picture is now stored in a better way

catavatar/catavatar.php
We don't need the caching at this place, since we do not link to the "catavatar" url in public anymore. So the code can be cleaned. A possible next step could be the use of PNG and especially transparency for the background - but not in this PR.
=> Catavatar: Code/functionality cleanup

membersince/membersince.php, smileybutton/smileybutton.php
Depends on https://github.com/friendica/friendica/pull/4951
=> Replace current_theme() and current_theme_url() calls

advancedcontentfilter/advancedcontentfilter.php, advancedcontentfilter/templates/settings.tpl
Follow-up to #586
Related to https://github.com/friendica/friendica/issues/4709
Regression introduced by https://github.com/friendica/friendica/pull/4951
=> [advancedcontentfilter] Fix various error messages

twitter/twitter.php
This works together with PR https://github.com/friendica/friendica/pull/4981
=> "Remote-self" is now working for Twitter as well

pumpio/pumpio.php
"deleteById" will be used only internally in the future. Additionally the code had been simplified.
=> Changed function that will be private in the future

twitter/twitter.php
This fixes friendica/friendica#4627 (which is allready closed but not fixed yet).
Any suggestions for improvements are highly welcome.
=> Catch TwitterOAuthException thrown by Abraham/TwitterOAuth

mathjax/mathjax.js, mathjax/mathjax.php
This uses the JS hook mechanism from PR https://github.com/friendica/friendica/issues/5179 to solve issue https://github.com/friendica/friendica/issues/5118
=> 5118 Implement MathJax JS hook to update contents after live update

advancedcontentfilter/advancedcontentfilter.php
We have to get rid of the the old item function calls.
=> advancedcontentfilter: Abstraction for the item call

twitter/twitter.php
Fixes the following notice:
`PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/friendica/friendica/friendica/addon/twitter/twitter.php on line 1581`
=> Bug fix php72 notice twitter

advancedcontentfilter/advancedcontentfilter.php, mailstream/mailstream.php, pumpio/pumpio.php, statusnet/statusnet.php, twitter/twitter.php, windowsphonepush/windowsphonepush.php
Additionally the touched addons are partly reworked. For example the notification part had been removed since it is done directly in the item class for a longer time.
=> Use of the new item class functions

pumpio/pumpio.php, twitter/twitter.php
Like in the corresponding PR in the core many SQL calls have been replaced by appropriate function calls.
=> And some more item class calls in the addons

mailstream/mailstream.php, statusnet/statusnet.php, viewsrc/viewsrc.php
We are seeing the light at the end of the tunnel ...
=> Some more replaced item SQL queries

langfilter/langfilter.php
Has to be accepted at the same time as PR https://github.com/friendica/friendica/pull/5302
=> "langfilter" uses the new "language" field as well

blockem/blockem.php, fromgplus/fromgplus.php, jappixmini/jappixmini.php, langfilter/langfilter.php, leistungsschutzrecht/leistungsschutzrecht.php, newmemberwidget/newmemberwidget.php, openstreetmap/openstreetmap.php, pumpio/pumpio.php, rendertime/rendertime.php, showmore/showmore.php, statusnet/statusnet.php, twitter/twitter.php, xmpp/xmpp.php
And here the same for the addons. I hadn't changed any styling issue by purpose, since we still have a huge open PR - and I want to avoid merge conflicts.
=> Avoid warnings in addons

mastodoncustomemojis/mastodoncustomemojis.php
This adds some `use` lines to the plugin to improve code readability.
=> [mastodon-custom-emojis] more "import" (use) used

advancedcontentfilter/advancedcontentfilter.php, buffer/buffer.php, catavatar/catavatar.php, diaspora/diaspora.php, ifttt/ifttt.php, libertree/libertree.php, public_server/public_server.php, pumpio/pumpio.php, statusnet/statusnet.php, tumblr/tumblr.php, twitter/twitter.php, windowsphonepush/windowsphonepush.php, wppost/wppost.php
Part 2 of https://github.com/friendica/friendica/issues/5410
Depends on https://github.com/friendica/friendica/pull/5422
=> [multiple] Rename Friendica\Database\dba to Friendica\Database\DBA

js_upload/js_upload.php
The js-Uploader needs to make clear that multiple files can be uploaded, reword button.
=> [js_upload] Better wording for mass-upload photos button.

blockem/blockem.php
- used `use Friendica\App;`
- used proper type-hints
- added spaces and curly braces for better readability
=> [blockem] Cleanups:

pumpio/pumpio.php
Fixes/imports:
- added curly braces and spaces for better readability
- merged 2 `if()` blocks into one for lesser nested code blocks
- added type-hint `App` and `array` where applyable
- better "import" (`use` under PHP) classes and not reference them directly,
reducing and improving readability
=> [pumpio] Fixes/imports:

advancedcontentfilter/advancedcontentfilter.php
Part 3.1 of https://github.com/friendica/friendica/pull/5410
Depends on https://github.com/friendica/friendica/pull/5431
=> [advancedcontentfilter] Rename DBA::inArray to DBA::toArray

advancedcontentfilter/advancedcontentfilter.php, catavatar/catavatar.php, diaspora/diaspora.php, forumdirectory/forumdirectory.php, ifttt/ifttt.php, mailstream/mailstream.php, public_server/public_server.php, pumpio/pumpio.php, statusnet/statusnet.php, twitter/twitter.php, viewsrc/viewsrc.php
Part 3.2 of https://github.com/friendica/friendica/pull/5410
Depends on https://github.com/friendica/friendica/pull/5438
=> Remove DBM class

diaspora/diaspora.php, forumdirectory/forumdirectory.php, gravatar/gravatar.php, jappixmini/jappixmini.php, libravatar/libravatar.php, mailstream/mailstream.php, public_server/public_server.php, pumpio/pumpio.php, remote_permissions/remote_permissions.php, statusnet/statusnet.php, testdrive/testdrive.php, twitter/twitter.php, widgets/widget_like.php, widgets/widgets.php
Part 4.1 of https://github.com/friendica/friendica/pull/5410
Depends on https://github.com/friendica/friendica/pull/5439
=> Remove dbesc()

curweather/curweather.css, curweather/curweather.php, curweather/templates/widget.tpl
See issue [friendica#5473](https://github.com/friendica/friendica/issues/5473) and PR #653.
=> [curweather] Fix widget layout. [friendica#5473]

mailstream/mailstream.php
This PR fixes logger level from no longer existing `LOGGER_NORMAL` to `LOGGER_INFO`.
=> [mailstream]: Fixed logger level NORMAL -> INFO

diaspora/diaspora.php
Followup to #665, fixing parser error.
=> [diaspora]: Ops, fixed parser error. Followup to #665

widgets/widget_like.php
Part of https://github.com/friendica/friendica/issues/5410
Follow-up to #659
=> [widgets] Add missing use statement after dbesc conversion

buffer/buffer.php
Cleanups/fixes:
- purged deprecated x() and used !empty() instead
- add App as type-hint where missing
- added curly braces and spaces for better readability/code convention
- open curly brace after method/function should be next line
=> [bufffer] Got rid of x() and App type-hint (and more)

forumdirectory/forumdirectory.php
This PR does a few things:
- added type-hint `App`
- added type-hint `array` to $b
- used empty() instead of deprecated x()
- moved PAGE_* constants to class Friendica\Model\Profile
This PR **depends** on https://github.com/friendica/friendica/pull/5500 from main repository.
=> [forumdirectory] Fixes, type-hints and PAGE_* moval

pumpio/pumpio.php, statusnet/statusnet.php, twitter/twitter.php
This PR is related to https://github.com/friendica/friendica/pull/5490 and **depends** on it and is blocked by it!
=> [cross] Moved CONTACT_* constants to class Friendica\Model\Contact

tumblr/library/tumblroauth.php, tumblr/tumblr.php
- added type-hints for `App`
- added curly braces + spaces for better readability
- avoided to use deprecated x(), replaced with empty()
- converted multi single-line comment to single multi-line comment
- opening curly brace behind a function/method/class belongs into next line
=> [tumblr] Type-hints, curly braces and spaces added

buglink/buglink.php
=> [buglink]: Added type-hint 'App'

buffer/buffer.php, curweather/curweather.php, impressum/impressum.php, mastodoncustomemojis/mastodoncustomemojis.php
This PR does the needed changes to work with Proxy class rewrites in https://github.com/friendica/friendica/pull/5507 and **depends** on it therefor.
=> [global]: Proxy class has been introduced, need to fix these as well.

twitter/twitter.php
Related to https://github.com/friendica/friendica/issues/4584
Dependent on https://github.com/friendica/friendica/pull/5561
=> Restore source storing for Twitter conversations

twitter/twitter.php
Part of https://github.com/friendica/friendica/issues/5470
=> [twitter] Fix Read Error with exif_imagetype()

libravatar/README.md
As reported in friendica/friendica#5566 the libravatar service wont shutdown. This PR removes the information text about the shutdown from the addons README
=> Libravatar wont shutdown

morechoice/lang/C/messages.po, morechoice/morechoice.php
=> Added translation to morechoice

statusnet/statusnet.php
=> And again removed notices

notimeline/notimeline.php
And it is commented out in the core ...
https://github.com/friendica/friendica/blob/develop/include/items.php#L470
=> Disabling "notimeline" that is just the frontend for a setting

diaspora/Diaspora_Connection.php, diaspora/diasphp.php, mailstream/phpmailer/class.phpmailer.php
Fixes https://github.com/friendica/friendica/issues/4814
We now use a unified place for the temp files - with the exception of code in vendor folders.
=> Issue 4814: Unify the temp path location

buffer/buffer.php, diaspora/diaspora.php, fromgplus/fromgplus.php, ifttt/ifttt.php, jappixmini/jappixmini.php, pumpio/pumpio.php, statusnet/statusnet.php, twitter/twitter.php
[global] Rewrite:
- replace usage of deprecated NETWORK_* with Protocol::*
This PR **is related** to https://github.com/friendica/friendica/pull/5537
=> Stopped using deprecated NETWORK_*

js_upload/js_upload.php
if no album name is given the plugin uses an empty string for the album name (friendica will transform the empty string to the upload year)
=> js_upload: use empty string if no newalbum or album input element is found

advancedcontentfilter/advancedcontentfilter.php
See https://forum.friendi.ca/display/ec054ce7215b7d713899cca803427157
=> [advancedcontentfilter] Suppress rule evaluation errors

twitter/twitter.php
This avoids the situation in issue https://github.com/friendica/friendica/issues/4475
=> Issue 4475: Don't create empty twitter quotes

ifttt/ifttt.php, pumpio/pumpio.php, xmpp/xmpp.php
See post here: https://forum.friendi.ca/display/0b6b25a8945b8636bac842e008892922
=> Pumpio does connect now again.

ijpost/ijpost.php
The only change in functionality is line 137 (old 139) - the rest is just style.
=> Removed notice in ijpost and cleaned code

langfilter/langfilter.php
Everyday I think that we now should have removed them all ...
=> Where do these notices hide? Now one is removed

twitter/twitter.php
Fixes https://github.com/friendica/friendica/issues/4584
The problem happened when there was an animated gif and an external link in the same tweet. We incorrectly assumed that the media was related with the external link and only displayed a picture for it.
=> [twitter] Fix external link picture

twitter/twitter.php
Fixes https://github.com/friendica/friendica/issues/4014
We were using the plaintext of the post before the quoted tweet, which would strip all links. We are now using the rich text, which necessitated to prevent footer generation in the case of a quote tweet.
=> [twitter] Use rich text for quote tweet

advancedcontentfilter/composer.json, blackout/lang/fr/messages.po, buffer/lang/fr/messages.po, curweather/lang/fr/messages.po, twitter/composer.json
Addon pendant of https://github.com/friendica/friendica/pull/5764
=> [various] Update "mrpetovan" email address

blogger/blogger.php, dwpost/dwpost.php, ijpost/ijpost.php, libertree/libertree.php, ljpost/ljpost.php, mastodoncustomemojis/mastodoncustomemojis.php, openstreetmap/openstreetmap.php, pumpio/pumpio.php, wppost/wppost.php
Fixing https://github.com/friendica/friendica/issues/5879
=> Bugfixing for CurlResult

diaspora/diaspora.php, libertree/libertree.php, mailstream/mailstream.php, notifyall/notifyall.php, pumpio/pumpio.php, securemail/securemail.php, statusnet/statusnet.php, twitter/twitter.php, xmpp/xmpp.php
should fix friendica/friendica#5881
=> Adoption of get_hostname changes for diaspora bridge

mastodoncustomemojis/mastodoncustomemojis.php
Fixes https://github.com/friendica/friendica/issues/5890
=> [mastodoncustomemojis] Ensure enoji array keys are set

notifyall/notifyall.php, openstreetmap/openstreetmap.php
Because of https://github.com/friendica/friendica/pull/5905
-> notifyall successfully tested
=> Remove z_root()

fromgplus/fromgplus.php
Fixes https://github.com/friendica/friendica/issues/5908
=> [fromgplus] Fix Undefined property: stdClass::$published notice

twitter/twitter.php
Fixes https://github.com/friendica/friendica/issues/5857
=> [twitter] Fix Undefined property: stdClass::$media_id_string notice

statusnet/statusnet.php
Addresses https://github.com/friendica/friendica/issues/5932#issuecomment-429897811
=> [statusnet] Fix Undefined variable: id

buffer/bufferapp.php
Addresses https://github.com/friendica/friendica/issues/5932#issuecomment-429896514
=> [buffer] Fix Undefined offset: 504 notice

twitter/twitter.php
Follow-up to #754
Addresses https://github.com/friendica/friendica/pull/5942#issuecomment-430753579
=> [twitter] Shorten foreign share mention

advancedcontentfilter/advancedcontentfilter.php, gravatar/gravatar.php, libravatar/libravatar.php, public_server/public_server.php, windowsphonepush/windowsphonepush.php
Related to https://github.com/friendica/friendica/pull/5946
=> Move include/security to /src/Core/Authentication.php and /src/Util/Security.php

curweather/curweather.php, openstreetmap/openstreetmap.php
- Replaced every `CACHE_` definition
Part of https://github.com/friendica/friendica/pull/5977
=> Move Global Functions - Part 3

twitter/twitter.php
Part of https://github.com/friendica/friendica/issues/5913
=> [twitter] Add missing parameter to converShare

advancedcontentfilter/advancedcontentfilter.php, public_server/public_server.php
Depends on https://github.com/friendica/friendica/pull/5981
=> [various] Move dbstructure to php

catavatar/catavatar.php
see https://github.com/friendica/friendica/pull/6009 for further details
=> resize images to 300px for frio compliance

blackout/blackout.php, impressum/impressum.php, notifyall/notifyall.php, startpage/startpage.php, statusnet/statusnet.php, twitter/twitter.php
Bugfix for https://github.com/friendica/friendica/issues/6015
=> Bugfix - Replacing goaway()

forumdirectory/forumdirectory.php
Depends on https://github.com/friendica/friendica/pull/6017
=> [forumdirectory] Use Content\Pager instead of App->pager

googlemaps/googlemaps.php
missing semi-colon
related to https://github.com/friendica/friendica/pull/3878
=> Logger: Bug fix

advancedcontentfilter/advancedcontentfilter.php, blackout/blackout.php, buffer/buffer.php, catavatar/catavatar.php, curweather/curweather.php, forumdirectory/forumdirectory.php, fromgplus/fromgplus.php, geocoordinates/geocoordinates.php, gravatar/gravatar.php, impressum/impressum.php, irc/irc.php, langfilter/langfilter.php, libravatar/libravatar.php, mailstream/mailstream.php, mathjax/mathjax.php, newmemberwidget/newmemberwidget.php, notifyall/notifyall.php, openstreetmap/openstreetmap.php, pageheader/pageheader.php, piwik/piwik.php, public_server/public_server.php, remote_permissions/remote_permissions.php, securemail/securemail.php, statusnet/statusnet.php, tumblr/tumblr.php, twitter/twitter.php, webrtc/webrtc.php, widgets/widget_like.php, widgets/widgets.php, xmpp/xmpp.php
functions split from text.php to Core\Renderer
Related to: https://github.com/friendica/friendica/issues/3878
Requires: https://github.com/friendica/friendica/pull/6053
=> Core Renderer Class

blogger/blogger.php, dwpost/dwpost.php, ijpost/ijpost.php, ljpost/ljpost.php, pumpio/pumpio.php, qcomment/qcomment.php, wppost/wppost.php
implement functions moved to xml class
Related to: https://github.com/friendica/friendica/issues/3878
requires: https://github.com/friendica/friendica/pull/6070
=> XML functions were moved

wppost/wppost.php
Fixes https://github.com/friendica/friendica-addons/pull/770
Self merging, since it causes a WSOD.
=> Fix PR 770

widgets/widget_friendheader.php, widgets/widget_friends.php
update function calls to new class
Related to:  https://github.com/friendica/friendica/issues/3878
Requires: https://github.com/friendica/friendica/pull/6085
=> Functions moved to HTML

blockem/blockem.php, buffer/buffer.php, forumdirectory/forumdirectory.php, geocoordinates/geocoordinates.php, gravatar/gravatar.php, ifttt/ifttt.php, impressum/impressum.php, libravatar/libravatar.php, newmemberwidget/newmemberwidget.php, openstreetmap/openstreetmap.php, piwik/piwik.php, public_server/public_server.php, pumpio/pumpio.php, remote_permissions/remote_permissions.php, showmore/showmore.php, statusnet/statusnet.php, superblock/superblock.php, tumblr/tumblr.php, twitter/twitter.php, webrtc/webrtc.php, wppost/wppost.php, xmpp/xmpp.php
implement functions from Strings class
Related to: https://github.com/friendica/friendica/issues/3878
Requires: https://github.com/friendica/friendica/pull/6102
=> Functions moved to Strings class

twitter/twitter.php
```PHP Notice:  Undefined property: stdClass::$id_str in .../addon/twitter/twitter.php on line 1807```
=> Avoid a notice in twitter.php 

blogger/blogger.php, buffer/buffer.php, diaspora/diaspora.php, libertree/libertree.php, pumpio/pumpio.php, statusnet/statusnet.php, tumblr/tumblr.php, twitter/twitter.php, wppost/wppost.php
Depends on PR https://github.com/friendica/friendica/pull/6108
=> Added a hook to check if the hook needs to be forked at all

wppost/wppost.php
Sometimes spaces are important ...
=> Fix posting to wordpress

jappixmini/jappixmini.php
See https://github.com/friendica/friendica/issues/5911#issuecomment-449949545
Also addresses https://github.com/friendica/friendica/issues/5932#issuecomment-449949670
=> Solves PHP warning "Use of undefined constant"

advancedcontentfilter/advancedcontentfilter.php, curweather/curweather.php, forumdirectory/forumdirectory.php, fromgplus/fromgplus.php, ifttt/ifttt.php, public_server/public_server.php, pumpio/pumpio.php, statusnet/statusnet.php, testdrive/testdrive.php, twitter/twitter.php, widgets/widget_like.php
Part of #6309
Depends on https://github.com/friendica/friendica/pull/6315
=> Bug/ remove include

ifttt/ifttt.php, impressum/impressum.php, widgets/widgets.php
Fixes https://github.com/friendica/friendica/issues/6334
Related to https://github.com/friendica/friendica/pull/6336
=> [various] Escape global function get_app calls

twitter/twitter.php
Fixes https://github.com/friendica/friendica/issues/4708
=> [twitter] Use original URL for link display

forumdirectory/forumdirectory.php
Dependent on https://github.com/friendica/friendica/pull/6390
=> [forumdirectory] Move Contact::PAGE_* constants to User::PAGE_FLAGS_*

blackout/blackout.php, notifyall/notifyall.php, startpage/startpage.php, statusnet/statusnet.php, twitter/twitter.php
Because of https://github.com/friendica/friendica/pull/5907
=> Replaced goaway() with System::redirect()

advancedcontentfilter/advancedcontentfilter.php, geonames/geonames.php, gravatar/gravatar.php, impressum/impressum.php, ldapauth/ldapauth.php, libravatar/libravatar.php, openstreetmap/openstreetmap.php, piwik/piwik.php, public_server/public_server.php, pumpio/pumpio.php, testdrive/testdrive.php, twitter/twitter.php
part of https://github.com/friendica/friendica/pull/6581
=> Config Refactoring

geonames/geonames.php, gravatar/gravatar.php, impressum/impressum.php, ldapauth/ldapauth.php, libravatar/libravatar.php, openstreetmap/openstreetmap.php, piwik/piwik.php, public_server/public_server.php, pumpio/pumpio.php, testdrive/testdrive.php, twitter/twitter.php
Used because of https://github.com/friendica/friendica/pull/6641
- used new `getConfigCache()`
- used new class directory
=> Moved method names & class

rendertime/rendertime.php
Part of https://github.com/friendica/friendica/pull/6707
FollowUp #808 
Fixing https://github.com/friendica/friendica/issues/6691
=> [rendertime] Bugfix Callstack

fromapp/lang/cs/messages.po, fromapp/lang/cs/strings.php, fromapp/lang/de/messages.po, fromapp/lang/de/strings.php, piwik/lang/cs/messages.po, piwik/lang/cs/strings.php, piwik/lang/de/messages.po, piwik/lang/de/strings.php
Updated the CS and DE translation of the
* fromapp
* piwik
addons.
=> translation updates

diaspora/Diaspora_Connection.php, irc/irc.php, pageheader/pageheader.php
Fixing https://github.com/friendica/friendica/issues/6338#issuecomment-459002901
Fixing https://github.com/friendica/friendica/issues/6338#issuecomment-464912016 (some more notices)
=> Avoid Notices

js_upload/js_upload.php
Fixing https://github.com/friendica/friendica/issues/6338#issuecomment-472373099
=> [js_upload] Fixing missing extension index

advancedcontentfilter/lang/sv/messages.po, advancedcontentfilter/lang/sv/strings.php, langfilter/lang/sv/messages.po, langfilter/lang/sv/strings.php
added SV translation of
* advancedcontentfilter
* langfilter
addons.
=> SV translation THX  Bjoessi

geonames/geonames.php, gravatar/gravatar.php, impressum/impressum.php, ldapauth/ldapauth.php, libravatar/libravatar.php, openstreetmap/openstreetmap.php, piwik/piwik.php, public_server/public_server.php, pumpio/pumpio.php, testdrive/testdrive.php, twitter/twitter.php
Part of https://github.com/friendica/friendica/pull/6920
=> Moving/Renaming ConfigCacheLoader to ConfigFileLoader

blogger/blogger.php, buffer/buffer.php, diaspora/diaspora.php, dwpost/dwpost.php, ijpost/ijpost.php, libertree/libertree.php, ljpost/ljpost.php, pumpio/pumpio.php, statusnet/statusnet.php, tumblr/tumblr.php, twitter/twitter.php, wppost/wppost.php
Related to https://github.com/friendica/friendica/pull/6903
Depends on https://github.com/friendica/friendica/pull/6931
=> [various] Replace HTML string by structured array in jot_networks hook

diaspora/diaspora.php, pumpio/pumpio.php, twitter/twitter.php
The "Queue" mechanism is some anachronism that we don't need anymore, since the worker can easily replace this functionality with less effort.
=> Replace the "Queue" mechanism with deferred workers

diaspora/diaspora.php, pumpio/pumpio.php, twitter/twitter.php
This is a follow up from PR https://github.com/friendica/friendica-addons/pull/839
=> Remove the queue from the addons

phpmailer/phpmailer.php
Resolves https://github.com/friendica/friendica/issues/5047
=> PHP Mailer: Add use statement

phpmailer/phpmailer.php
Develop not work with actual friendica master. I just added 2nd  param to ` Config::get` call.
=> Fix phpmailer compatibility with latest stable friendica

langfilter/lang/et/messages.po, langfilter/lang/et/strings.php, newmemberwidget/lang/et/messages.po, newmemberwidget/lang/et/strings.php, securemail/lang/et/messages.po, securemail/lang/et/strings.php
After the Estonian translation for the core is not over 50% and included, the translation for the
* newmemberwidget,
* securemail and
* langfilter
addons are added as well.
THX Rain Hawk
=> added Estonian translation THX Rain Hawk

forumdirectory/forumdirectory.php
Necessary because of https://github.com/friendica/friendica/pull/7072
=> Move mod/directory to src/Module/Directory

mailstream/mailstream.php, statusnet/statusnet.php, twitter/twitter.php
Addon pendant of https://github.com/friendica/friendica/pull/7074
=> [various] Remove /display/{nick}/{id} URL structure publishing

widgets/widget_like.php, widgets/widgets.php
Addon pendant of https://github.com/friendica/friendica/pull/7044/commits/9774c95b807eeae0a9f70ce6c75f3f20a5147673
=> [widgets] Remove superfluous $baseurl template variable

windowsphonepush/windowsphonepush.php
Depends on https://github.com/friendica/friendica/pull/7135
=> [windowsphonepush] Move Authentication::setAuthenticatedSessionForUser to Session::setAuthenticatedForUser

phpmailer/LICENSE, phpmailer/README.md, phpmailer/config/phpmailer.config.php, phpmailer/phpmailer.php
Redux of #858
Addon part of friendica/friendica#7023
Depends on friendica/friendica#7187
=> [phpmailer] Use new emailer hook "sent" property

phpmailer/LICENSE, phpmailer/README.md, phpmailer/config/phpmailer.config.php, phpmailer/phpmailer.php
#859 hadn't been switched to the correct branch.
=> Update 2019.06 rc with phpmailer PR

xmpp/xmpp.php
Includes #860
Closes https://github.com/friendica/friendica/issues/2528
Closes https://github.com/friendica/friendica/issues/3105
Closes https://github.com/friendica/friendica/issues/3717
=>  [xmpp] Mark addon as unsupported

mailstream/mailstream.php, pumpio/pumpio.php, statusnet/statusnet.php, twitter/twitter.php
Part of https://github.com/friendica/friendica/pull/7242
=> [various] Refactor url/fetchUrl parameter

twitter/twitter.php
Addresses https://github.com/friendica/friendica/issues/6918#issuecomment-502446217
=> [twitter] Fix undefined object notice

forumdirectory/forumdirectory.php
No longer available include file removed.
=> Removed no longer used include file

blockbot/blockbot.php
=> blockbot: Adding new bots to the blocklist

twitter/twitter.php
We now import picture descriptions from Twitter.
The export is most likely more complicated. So it will be covered in a separate PR.
=> Twitter: Import picture description

twitter/twitter.php
Fixes https://github.com/friendica/friendica/issues/7299#issuecomment-526944337
=> Check twitter details before showing it

twitter/twitter.php
See here: https://github.com/friendica/friendica/issues/7299#issuecomment-533789219
=> Fix notice in Twitter addon

mailstream/mailstream.php
After ignoring Friendica for a long time I'm trying to get up to speed with recent refactorings and get more of my code pushed upstream.  Here's some simple changes to use nicer logging functions in mailstream.
=> Modernise logging in mailstream plugin

tumblr/library/tumblroauth.php
See here: https://forum.friendi.ca/display/f3ad7b1c-815d-8f8e-c7a3-767649009994
=> tumblr: Now using https instead of http for the endpoints

forumdirectory/forumdirectory.php
Addon pendant of https://github.com/friendica/friendica/pull/7710
=> [forumdirectory] Remove direct access to $_SESSION['theme']

xmpp/xmpp.php
Addon part of https://github.com/friendica/friendica/pull/7727
=> [xmpp] Rename /manage module to /delegation

blogger/lang/ca/messages.po, blogger/lang/ca/strings.php, buffer/lang/ca/messages.po, buffer/lang/ca/strings.php, group_text/lang/ca/messages.po, group_text/lang/ca/strings.php, langfilter/lang/ca/messages.po, langfilter/lang/ca/strings.php
The CA translation for the blogger, buffer, group_text and langfilter addon was updated by obiolscat.
=> CA translation updated THX obiolscat

blogger/blogger.php, buffer/buffer.php, curweather/curweather.php, irc/irc.php, jappixmini/jappixmini.php, js_upload/js_upload.php, notifyall/notifyall.php, openstreetmap/openstreetmap.php, pumpio/pumpio.php, rendertime/rendertime.php, wppost/wppost.php, xmpp/xmpp.php
Part of https://github.com/friendica/friendica/issues/7190
=> [various] Replace deprecated defaults() calls by ?? operator

remote_permissions/remote_permissions.php
Part of https://github.com/friendica/friendica/pull/7765
=> [remote_permissions] Move expand_acl to ACLFormatter::expand()

mailstream/mailstream.php, pumpio/pumpio.php, statusnet/statusnet.php, twitter/twitter.php
Part of https://github.com/friendica/friendica/pull/7770
=> Move Activity definitions to constants

remote_permissions/remote_permissions.php
FollowUp https://github.com/friendica/friendica/pull/7765
Fixes https://github.com/friendica/friendica/issues/7781
Part of https://github.com/friendica/friendica/pull/7782
=> Check null for acl-fields

twitter/twitter.php
Just some improved logging with unchanged functionality.
=> Added logging to twitter addon

remote_permissions/remote_permissions.php
- Add nullable to expand() function again
- Add angle bracket support to toString()
=> [remote_permissions] Fix ACLFormatterTest

js_upload/js_upload.php, js_upload/templates/js_upload.tpl
Fixes https://github.com/friendica/friendica/issues/7880
- Move HTML to template
- Remove redundant uninstall method
- Enforce coding standards
- Add type-hinting
=> [js_upload] Rewrite addon after ACL changes

js_upload/templates/js_upload.tpl
Fixes https://github.com/friendica/friendica/issues/7888
=> [js_upload] Restore public image upload

statusnet/library/twitteroauth.php, tumblr/library/tumblroauth.php
- Addresses https://github.com/friendica/friendica/issues/7675#issuecomment-564562386
- Addresses https://github.com/friendica/friendica/issues/7675#issuecomment-564648263
=> [various] Use correct object class for Oauth token

twitter/twitter.php
Depends on https://github.com/friendica/friendica/pull/7777
=> Move Object\Image static methods to Util\Images

windowsphonepush/windowsphonepush.php
Part of https://github.com/friendica/friendica/pull/7907
=> [windowsphonepush] - Switch Authentication call

tumblr/tumblr.php
- Addresses https://github.com/friendica/friendica/issues/8000#issuecomment-568784745
=> [tumblr] Fix notice when submitting user settings

markdown/markdown.php
Fixes https://github.com/friendica/friendica-addons/pull/924#discussion_r361459823
=> Markdown: Escape some elements prior to sending them through Markdown

markdown/markdown.php
This should help with the "share" element problem.
=> Markdown: Protect some more elements from markdown parsing

openstreetmap/openstreetmap.php
This is a first fix to PR #927
=> Fix PR 927: Adds forgotten calls

blockem/blockem.php, blogger/blogger.php, buffer/buffer.php, curweather/curweather.php, diaspora/diaspora.php, dwpost/dwpost.php, forumdirectory/forumdirectory.php, jappixmini/jappixmini.php, js_upload/js_upload.php, mastodoncustomemojis/mastodoncustomemojis.php, pumpio/pumpio.php, smileybutton/smileybutton.php, statusnet/statusnet.php, tumblr/tumblr.php, twitter/twitter.php, xmpp/xmpp.php
Part of https://github.com/friendica/friendica/pull/8035
=> [various] Replace deprecated $a->page with DI::page()

calc/calc.php, fromapp/fromapp.php, gnot/gnot.php, group_text/group_text.php, ijpost/ijpost.php, impressum/impressum.php, infiniteimprobabilitydrive/infiniteimprobabilitydrive.php, irc/irc.php, krynn/krynn.php, libertree/libertree.php, ljpost/ljpost.php, newmemberwidget/newmemberwidget.php, notimeline/notimeline.php, nsfw/nsfw.php, numfriends/numfriends.php, openstreetmap/openstreetmap.php, piwik/piwik.php, planets/planets.php, qcomment/qcomment.php, randplace/randplace.php, remote_permissions/remote_permissions.php, showmore/showmore.php, startpage/startpage.php, superblock/superblock.php, viewsrc/viewsrc.php, windowsphonepush/windowsphonepush.php, wppost/wppost.php
Follow-up to #935
Part of https://github.com/friendica/friendica/pull/8035
Addresses https://github.com/friendica/friendica/issues/8000#issuecomment-569770878
=> [various] Replace remaining $a->page by DI::page()

ifttt/ifttt.php
Part of https://github.com/friendica/friendica/pull/8053
=> [ifttt] Remove get_app() in favor of DI::app()

testdrive/testdrive.php
Part of https://github.com/friendica/friendica/pull/8055
=> [testdrive] Remove get_server() in favor of Search::getGlobalDirectory()

advancedcontentfilter/advancedcontentfilter.php
Fixes https://github.com/friendica/friendica/issues/8090
- Fix broken reference to Friendica\Core\Cache
=> [advancedcontentfilter] Enable rule caching

openstreetmap/openstreetmap.php
Addresses https://github.com/friendica/friendica/issues/7998#issuecomment-573290305
=> [openstreetmap] Fix references to Cache

openstreetmap/openstreetmap.php
Part of https://github.com/friendica/friendica/pull/8129
- Introduce enum "Duration"
- Introduce enum "Type"
- Move "Cache\Cache" to "BaseCache"
=> CleanUp Cache namespace

blockbot/blockbot.php
This change allowes uptimerobot user agent to be allowed and fixes a bug which occures when good agents are similar with other agents. Example : "UptimeRobot/" and "oBot/".
=> feat(blockbot): ensure good agent are whitelisted and add uptimerobot

forumdirectory/forumdirectory.php, morechoice/morechoice.php, widgets/widget_friendheader.php, widgets/widget_friends.php
Part of https://github.com/friendica/friendica/pull/7817
Related to https://github.com/friendica/friendica/pull/8190
=> [various] New custom profile field feature

blockem/blockem.php, superblock/superblock.php
Part of https://github.com/friendica/friendica/pull/8186
=> [various] enotify: empty out fields instead of using "abort" for addons

securemail/securemail.php
Part of https://github.com/friendica/friendica/pull/8207
Fixes https://github.com/friendica/friendica/issues/8206
=> [securemail] Fix secure Mail addon

langfilter/langfilter.php
Address https://forum.friendi.ca/display/7c104781-855e-32d6-1bdd-aec097925772
- Rename langfilter.disable to langfilter.enable with backward compatibility
=> [langfilter] Add default values to form parameters

gnot/gnot.php, public_server/public_server.php, testdrive/testdrive.php
Part of https://github.com/friendica/friendica/pull/8239
=> [various] Move Notify "type" and "otype" into own enum classes

forumdirectory/forumdirectory.php
Depends on https://github.com/friendica/friendica/pull/8293
Also adds a change related to https://github.com/friendica/friendica/pull/8261
=> [forumdirectory] Add L10n parameter to Pager constructor call

public_server/public_server.php
To rise awareness about potential problems, as discussed in the admin forum. Relates to https://github.com/friendica/friendica/issues/8312.
=> Added warning

forumdirectory/forumdirectory.php, widgets/widget_friendheader.php, widgets/widget_friends.php
Related to https://github.com/friendica/friendica/pull/8146
Forgot to submit it, mostly because they didn't have to be merged at the same time.
=> [various] Remove redundant profile_uid field from profile query

advancedcontentfilter/doc/advancedcontentfilter.md, buglink/buglink.php, irc/irc.php, openstreetmap/openstreetmap.php
Part of https://github.com/friendica/friendica/issues/8323
Related to https://github.com/friendica/friendica/pull/8337
=> [various] Add rel="noopener noreferrer" to all target="_blank" links

widgets/templates/widget_like.tpl, widgets/widget_like.php
Part of https://github.com/friendica/friendica/issues/8318
Related to https://github.com/friendica/friendica/pull/8319
=> [widget_like] Add support for system.hide_dislike user config key

twitter/twitter.php
We now do fetch the relation between the user and the twitter contact. Additionally some improvements had been done to the contact update as well.
=> Twitter: Fetch the contact relation

advancedcontentfilter/advancedcontentfilter.php, advancedcontentfilter/src/middlewares.php
Fixes https://github.com/friendica/friendica/issues/8396
=> [advancedcontentfilter] Update HTTPException handling

pumpio/pumpio.php, twitter/twitter.php
Part of https://github.com/friendica/friendica/issues/7134
Depends on https://github.com/friendica/friendica/pull/8359
=> [pumpio] Rename Item::delete to Item::markForDeletion

showmore_dyn/lang/C/messages.po, showmore_dyn/lang/de/strings.php, showmore_dyn/showmore_dyn.css, showmore_dyn/showmore_dyn.js, showmore_dyn/showmore_dyn.php, showmore_dyn/templates/settings.tpl
Initial implementation as addon.
=> [WIP] #8374: Limit post content by rendered height instead of number of characters

twitter/twitter.php
- Uses Twitter-provided entity indices to avoid blanket string replacement and unwarranted tag search
Closes https://github.com/friendica/friendica/issues/8470
Depends on https://github.com/friendica/friendica/pull/8471
=> [twitter] Rework twitter_expand_entities
