friendica/friendica-addons

statistics_json/statistics_json.php
Additionally the database version is added to the version number to better be able to see if a system is on the stable or the develop branch.
=> Bugfix: The item counter doubled the value if the global community was active

convpath/convpath.php, pumpio/pumpio.php, statusnet/statusnet.php, twitter/twitter.php
Hopefully this reduces the problem of mirrored posts that were originally posted from friendica.
Additionally I set "convpath" to unsupported since it is obsolete through the ssl settings we added in 3.3.2.
=> GNU Social, Pump.io, Twitter: Improved check for duplicated posts

pumpio/pumpio.php
When comments were imported from pumpio they hadn't had "pumpio" as network source.
=> pumpio-Bugfix: Comments had a wrong network value in some cases

libertree/libertree.php
The libertree source name now consists of the hostname and the application name. I think that this is nicer.
=> New source name for libertree

fromgplus/fromgplus.php, gpluspost/gpluspost.php, pumpio/pumpio.php, statusnet/statusnet.php, statusnet/templates/admin.tpl, twitter/templates/admin.tpl, twitter/twitter.php
In the past the problem existed that a bad configuration of the connectors lead to the situation of a posting loop. This shouldn't now happen anymore for pump.io, GNU Social and Twitter. The system now fetches the application name from the last post and writes it in the configuration. This should now be bullet proof.
Google+ was a different problem. There the system sometimes detected a posting loop where there was none.
=> Improved loop detection for Google+, Pump.io, Twitter and GNU Social

fbpost/README.md, fbpost/fbpost.php
The issue https://github.com/friendica/friendica/issues/1416 reported a bug that postings from hidden groups were posted through the mirror function. I guess this was a problem inside of Facebook. But additionally the code was improved.
The permissions for the Facebook app was changed to make it compatible to Facebook's new requirements. These new permissions don't allow anymore the synchronization via "fbsync" since Facebook doesn't allow this after 30th of April anymore
=> Facebook: Improved privacy detection, changed permissions

diaspora/diaspora.php
So this addon is set to "unsupported"
=> The function to post to Diaspora doesn't support newer versions

statusnet/statusnet.php
We really should name a network by its current name. See issue https://github.com/friendica/friendica/issues/1744 - (although this refers to the homepage)
=> Statusnet is now GNU Social

twitter/twitter.php
This skips the import of some posts that would otherwise show up two times on the network page by
- don't import posts that have been send by the user via Friendica to Twitter
- don't import posts that will be mirrored to the users profile wall
=> Twitter: skip duplicate posts when importing hometimeline

langfilter/LICENSE, langfilter/README.md, langfilter/lang/C/messages.po, langfilter/langfilter.php, langfilter/templates/settings.tpl
This addon is based on the NSFW filter but collapses postings based on the detected language instead of a list of words.
not exactly what friendica/friendica#1778 describes as this is not a per contact setting, but it filters the postings in unspoken languages.
=> Langfilter

twitter/twitter.php
=> Twitter: The destroy command generates an error

langfilter/lang/C/messages.po, langfilter/langfilter.php, langfilter/templates/settings.tpl
I'd actually want to add a new setting to restrict filtering to posts for which the language guessers has a minimum confidence
=> Cleanup implementation of langfilter_prepare_body, and fix a typo

jappixmini/jappixmini.php, rendertime/rendertime.php
The minimal mode is used for example in the bookmarklet. It doesn't look nice if there would be a chat window there.
=> Don't show the rendertime data and jappix in minimal mode.

pumpio/pumpio.php
The sync is now executed externally - so it has to be tested if the plugin is enabled.
=> Only execute the sync if the pumpio plugin is enabled

rendertime/rendertime.php
Now the addon shows the callstack when the following parameter is set:
````
$a->config['rendertime']['callstack'] = true;
````
This will work with the currently open pull request in the core.
=> Rendertime: Optionally show the callstack

smileybutton/smileybutton.php
this is needed to make the smiley preview an inline-block (which is part of https://github.com/friendica/friendica/pull/2322)
The other themes are not affected by this.
=> make smileybutton part of the div profile-smiley-wrapper

curweather/curweather.php, curweather/lang/C/messages.po
Strings containing the °C or °F are now &deg;C and &deg;F when passed to the translation function. Also the messages.po file for the addon was regenerated.
for friendica  ##2402
=> encode the degree for the translation

showmore/showmore.php
add some classes to the html elements of the showmore addon to have better possibilities for styling.
BTW
Since showmore can only appear once in one post/comment couldn't we use the item-id for `$rnd` instead of a random string?
=> showmore: add css classes to elements

rendertime/rendertime.php
This should fix the negative times for "Other" since the core was already changed.
=> Rendertime: Show the value for session creation

notifyall/notifyall.php, notifyall/templates/notifyall_form.tpl
This is a port of Hubzillas hubwall addon.
It allows the admin to send emails to every member of a friendica instantce. This could be useful e.g. to inform the members about future maintenance downtime.
all credits going to Mike Macgirvin as author of the addon
=> port hubzillas hubwall addon to friendica (notifyall)

forumdirectory/templates/forumdirectory_item.tpl
regarding the 0 in the postal code from friendica/friendica#1494
* only show fields set
* `country-name` and `postal-code` need other notation because of the dash in the variable name
=> only show address information when set

langfilter/langfilter.php, langfilter/templates/settings.tpl
No more "lol" messages filtered (with filter message being longer than the actual message)
NOTE: implementation might be cleaned up but I'm out of time (specifically: the way defaults are handled, currently rewritten in many places)
=> Add minimum post body length setting to language filter

ifttt/ifttt.php
This PR fixes the misleading IFTTT info panel by adding the required user's nickname to the IFTTT callback URL.
=> [ifttt] Add missing nickname in the callback URL

twitter/twitter.php, twitter/twitter_sync.php
When the worker is enabled the call for fetching the timeline and the mentions is split into multiple calls. This is done to shorten the process execution time - which is very important with the frontend worker.
=> Twitter: The sync process is split into several short processes

pumpio/pumpio_sync.php, securemail/securemail.php, twitter/twitter_sync.php
This PR updates addons to make them compatible with the release 3.5.2 of Friendica.
It all boils down to using namespaces to invoke the App class. Fortunately, very few addons do that and were disrupted on server running Friendica develop branch.
This PR should be merged after the 3.5.2 release.
=> Move app to src

securemail/securemail.php
The securemail addon was overwriting all of the user settings form
rendered before it. I've added a concatenation operator to ensure
we're not losing any content on this page.
=> Fix rendering of securemail user settings

nsfw/README
As already mentioned in the README file, the usage of of capturing parathese produces errors, so it's important to use grouping parantheses there instead.
=> Grouping parentheses instead of capturing parentheses

fromgplus/fromgplus.php, ifttt/ifttt.php, mailstream/mailstream.php, pumpio/pumpio.php, statusnet/statusnet.php, widgets/widgets.php
Some addons were missed during the changes... now all should use the PConfig::delete call.
=> use more PConfig::delete

forumdirectory/forumdirectory.php
It was part of the old template engine.
=> The function "template_escape" doesn't exist anymore.

membersince/membersince.php
see the title.
The membersince data will be added after the last entry of the content of the `#profile-content-standard` div.
I would like to have it inserted right after the `fullname` entry. But I could not manage it. Maybe someone else can have a look.
=>  membersince addon works now with frio

namethingy/namethingy.php
This addon doesn't work anymore since it is just a redirector to a website which doesn't exist anymore.
=> Namethingy is now unsupported

membersince/membersince.php
The membersince addon was moved to core (https://github.com/friendica/friendica/pull/4432). So we can mark it as unsupported.
=> membersince: mark membersince as unsupported because it is now in core

public_server/public_server.php
=> Missed "use"

openstreetmap/openstreetmap.php, openstreetmap/templates/admin.tpl
This belongs to PR https://github.com/friendica/friendica/pull/4636
Additionally to the improvements for exports to other networks, there is now a caching of requests to avoid restrictions by the OSM servers.
=> Results are now cached, format limits to other networks are respected

twitter/twitter.php
Formerly the API call for sending posts with media had been different. Since we are now using not only the same commands but also the same library, we can clean up the code.
=> Twitter: Code for sending media to Twitter has been optimised

blockem/blockem.php, blockem/lang/C/messages.po, fromgplus/fromgplus.php, fromgplus/lang/C/messages.po, langfilter/lang/C/messages.po, langfilter/langfilter.php, nsfw/lang/C/messages.po, nsfw/nsfw.php, showmore/lang/C/messages.po, showmore/showmore.php
See: https://friendica.mrpetovan.com/display/735a2029715ab80d1874cf6808556656
Depends on https://github.com/friendica/friendica/pull/4722
Please review the translation strings I added, they may not be the best way of presening the content filtering reasons.
Additionally, the showmore addon now disabled when there is a content-filter applied because of display incompatibility.
=> Add content_filter hook

buffer/buffer.php, langfilter/langfilter.php, statusnet/statusnet.php, twitter/twitter.php
Depends on https://github.com/friendica/friendica/pull/4881
Part of https://github.com/friendica/friendica/issues/4867
This PR contains the backward-incompatible changes introduced in https://github.com/friendica/friendica/pull/4881 as well as an improvement to the `langfilter` addon that now uses the plaintext body to calculate the minimum body length, using the same text transformation function as the language detection does.
=> Guess language from plaintext

notifyall/notifyall.php
enclose the *senders name* construct
$nodename, Administrator
with quotation marks so it does not get interpreted as multible email addresses.
this might solve friendica/friendica#4976
=> notifyall: enclose senders name in quotation marks

langfilter/langfilter.php
As mentioned in friendica/friendica#4710 there should not be a preset for the filtered languages.
=> langfilter: dont add languages when none are set to the settings

mastodoncustomemojis/README.md, mastodoncustomemojis/mastodoncustomemojis.php
Depends on https://github.com/friendica/friendica/pull/5372
This is a new addon to add Mastodon custmo emoji support. For each OStatus post, this addon will attempt to get the custom emojis of the author's server from the cache (1 week duration) then from the Mastodon API endpoint.
=> [mastodoncustomemojis] Add new addon

buffer/buffer.php, leistungsschutzrecht/leistungsschutzrecht.php, pumpio/pumpio.php, statusnet/statusnet.php, tumblr/tumblr.php, twitter/twitter.php
This is mostly about removing notices. Additionally it is a fix for some issue. Normally when finally deleting an item, also the content and activity data is deleted. This doesn't work for twitter posts that we delete earlier by the addon. Therefore we have to delete the content here as well. We should move this action into the item class in the future.
=> Some notices had been removed / expiring of item related tables in twitter

mastodoncustomemojis/mastodoncustomemojis.php
This fixes an E_NOTICE (`error_reporting(E_ALL)` was used) in an addon.
=> [mastodon-custom-emojis] Fixes E_NOTICE for absent 'port' element

curweather/templates/widget.tpl
The weather widget uses h4 instead of h3 for the aside. Fix that.
Old:
New:
=> Unify header level for weather widget.

curweather/curweather.php, curweather/templates/widget-error.tpl
Fix several issues in curweather widget:
- When the widget can not load weather data, it shows a notice, this notice is shown on every page load. Also the widget is plain and blank and needs to be formated properly.
* Fix: Store notification-shown-state in session and show only once per session. (See https://github.com/friendica/friendica-addons/compare/develop...astifter:curweather_fix_header?expand=1#diff-5cd1ef666d6ce6004e4e355947ed8d10R37)
* Fix: Restyle error widget:
Old:
- Fix whitespace in PHP file.
=> [curweather] Only shown notice about unavailable weather once per session.

blogger/blogger.php
- used `use Friendica\App;`
- added type-hints for `App` and `array` where applyable
- removed extra space
- added other spaces
=> [blogger] Cleanups:

diaspora/diaspora.php
This cleans up the following:
- added curly braces/spaces for better readability
- don't use count() when you can use `DBA::isResult()`
- used proper type-hints `App` and `array`
- "imported" Friendica\App
=> [diaspora] Cleanups and type-hinting

xmpp/xmpp.php
Fixes:
- rewrote from deprecated x() to empty()
- added some empty lines for better readability
- used single quotes
=> [xmpp] x() is deprecated, let's use empty()?

curweather/curweather.php
Fixes/rewrites:
- install/uninstall functions moved up (common across addons)
- Added `App` as type-hint for $a and no & (call-by-reference) anymore
- use empty() instead of deprecated x()
- opening curly brace belongs into new line after function/method declaration
- added a lot other curly braces for better readability
- added spaces and empty lines
=> [curweather] x() no longer used and more

dwpost/dwpost.php
- used type-hint `App` and no call-by-reference
- converted spaces -> tab for indenting
- DBA::isResult() used instead of empty/count/...
- added curly braces and spaces for better readability
- opening curly brace after function/method/class belongs into new line
- converted multiple single-line comments to single multi-line comment
=> [dwpost] Cleanups and type-hint rewrite

twitter/twitter.php
Fixes part of https://github.com/friendica/friendica/issues/4708
We used to replace URL display in tweets by the fully expanded URL and it wasn't right.
=> [twitter] Keep original display URL after link expansion

statusnet/statusnet.php
Should fix https://github.com/friendica/friendica/issues/3535
=> Don't use the GNU Social address if the connector isn't activated

twitter/twitter.php
Due to the way that shared posts from Twitter are looking in Friendica, this caused visual problem with "remote self", since these posts had't been recognizable as shared posts.
=> Remote self on Twitter will now only work with original content

blockem/blockem.php
The double quotes are only used for the settings of Blockem and Superblock. This is inconsistent from my point of view.
Please check very careful what I have done. I am a bloody amateur. :-)
=> Blockem: Removing the double quotes around setting's name

superblock/superblock.php
The double quotes are only used for the settings of Blockem and Superblock. This is inconsistent from my point of view.
Please check very careful what I have done. I am a bloody amateur. :-)
=> Superblock: Removing the double quotes around setting's name

mastodoncustomemojis/mastodoncustomemojis.php
Part of https://github.com/friendica/friendica/issues/5653
The weeklong TTL for emoji caching meant that new emojis wouldn't appear in Friendica at most 1 week after they would be introduced on the remote Mastodon instance.
=> [mastodoncustomemojis] Reduce cache TTL to prevent raw emojis display

twitter/twitter.php
Fixes #3218
Depends on https://github.com/friendica/friendica/pull/5942
The two new addon functions handles respectively mentions (native or foreign) and foregn reshares, avoiding to mentions random accounts based on the foreign contact username.
=> [twitter] Normalize mentions/foreign reshares

leistungsschutzrecht/README.md, leistungsschutzrecht/leistungsschutzrecht.php
There is a new config value to control the new behaviour.
Question: Where do we document this setting?
=> Leistungsschutzrecht: Optionally suppress pictures

cookienotice/templates/settings.tpl
In the cookiemessage settings the description field containes HTML formatting which got escaped.
This PR applies the `nofilter` to the template.
=> nofilter applied to fixed description

rendertime/rendertime.php
Following fixes has been applied:
- `$a->performance['id']` is outdated, there is now `$a->getProfiler()->get('id')`
- `AS` is no constant but a keyword (see `foreach()`)
- added curly braces
=> [rendertime] Ported to new Profiler class

INSTALL.txt
In INSTALL.txt a call to bin/composer.phar is documented, but neither is it necessary nor possible to call composer for addons.
=> Remove invalid call to composer

piwik/README.md, piwik/piwik.php
This PR reflects the name change of the piwik project to matomo in the README and header of the addon to both variants of the name are rused.
=> piwik is called matomo nowadays

blogger/blogger.php
We deprecate this addon for now. Possibly in the ~~past~~ future someone wants to implement the OAuth mechanism.
=> Blogger doesn't support XMLRPC anymore

twitter/twitter.php
It can happen that due to a timeout situation the twitter synchronisation is moved to a lower priority. This behaviour is mostly okay, but not here. So we enforce the priority here.
=> Enforce priority for Twitter synchronisation

blackout/README.md, blackout/blackout.php, blackout/lang/C/messages.po, blackout/templates/admin.tpl
I realized, that many of the translation work for the addon was not applied. This is now fixed.
Additionally some more strings, the notes for the admin, were made translate-able. Furthermore the templates were adjusted to the variable replacement possibilities that exist nowadays.
The old note about the requirement of PHP 5.3 or above was removed as Friendica nowadays expects PHP 7 or higher.
=> blackout addon: bugfix translation was not applied

twitter/twitter.php
Twitter retweets now are looking reshared posts via AP or Diaspora.
=> Twitter: Use the new reshare mechanism for retweets

curweather/curweather.php
The API result from openweathermap can either be "celsius" or "metric" to signal the usage of Celsius scale for the temperature in contrast to °F. Both replies are now handled accordingly.
=> API response celsius and metric both mean to use °C as unit for the temperature

cookienotice/cookienotice.php, pageheader/pageheader.php
Follow-up to #854 
Fix WSOD when submitting admin add-on settings for cookienotice and pageheader.
=> [various] Fix *_addon_admin_post parameters

pumpio/pumpio.php, statusnet/statusnet.php, twitter/twitter.php
The gcontact table shouldn't be flooded with contacts from non federated networks. It had been added in the past since it had been the plan to store every contact there that ever had posted. But that had been replaced by the public contacts.
There will be following PRs in the core that will address the same case as well.
=> Don't store non federated contacts in gcontact

geonames/geonames.php, gravatar/gravatar.php, impressum/impressum.php, ldapauth/ldapauth.php, libravatar/libravatar.php, openstreetmap/openstreetmap.php, phpmailer/phpmailer.php, piwik/piwik.php, public_server/public_server.php, pumpio/pumpio.php, testdrive/testdrive.php, twitter/twitter.php
Depends on https://github.com/friendica/friendica/pull/7313
I reverted the namespace move to `Config\`  - which I introduced some time ago for some more ConfigFile-Logic -  because it's really unnecessary!
=> [various] Namespace ConfigFileLoader

blockbot/blockbot.php, blockbot/templates/admin.tpl
Two more systems are added. Additionally the addon now has got a config page. On this page the admin can decide to block the software GabSocial. For only blocking dedicated Gab instances the server blocklist is the better choice. This here is the sledgehammer method :-)
=> Admin config setting added for blockbot, added option to block gabsocial

twitter/twitter.php
The setting to create users should control that you only see Twitter posts from selected users. This hadn't really worked well. Now it does.
=> Twitter: Better respect "create user" setting

mailstream/mailstream.php
With the new ActivityPub stuff, mailstream sends me annoying duplicate messages from Twitter just saying that someone retweeted the previous message.  I think the simplest way to get rid of these is to not send messages that don't have plinks.  If there's no plink you can't click the link to the original message, so they'll always be kinda crippled.
I also added debug messages explaining why mailstream ignores posts, to aid debugging this feature in future if it misfires.
=> [mailstream] Do not send "announce" messages

mailstream/mailstream.php
The filenames used in mailstream sometimes end up looking like "file.jpg?param=123" because I was calling basename on a URL.  This version uses parse_url to get rid of the URL paramters.
=> [mailstream] Remove URL parameters when extracting image filenames

mailstream/mailstream.php
I noticed that mails from mailstream are only viewable in an HTML-capable mail reader.  Some people disable HTML for security reasons, so to support that this one-liner just dumps the BB code as alt-text.
=> [mailstream] Include BB code as plaintext

mailstream/mailstream.php
The new release broke mailstream's feature for including images as attachments.  My fault for not testing against develop earlier I guess :(
=> [mailstream] Support new img format with alt text

gnot/gnot.php, gnot/templates/settings.tpl
This PR adds the missing HTML to the gnot addons settings block to make it collaps-able.
See discussion [in the support forum](https://forum.friendi.ca/display/e18176ef-195d-9494-9535-ff2105792235).
=> [gnot] Make settings collapsible

discourse/README, discourse/discourse.php, discourse/templates/settings.tpl
Discourse has got some mailing list mode, so that you can participate via mail client as well. We use this as a base for this addon. Although Discourse has a very mighty API, the write access is not enabled by default for users. So we are using the mailing list mode instead - but we are fetching many data via API.
There are currently several things that should be improved over time, but it seems to work here fine for the last days.
=> Discourse Addon

buffer/buffer.php
See issue https://github.com/friendica/friendica/issues/7916
Buffer doesn't allow the registration of new applications via their API. So we deprecate that addon now. It will possibly still work for people with already registered API keys.
=> Issue 7916: Buffer is unsupported now

advancedcontentfilter/advancedcontentfilter.php
Fixes https://github.com/friendica/friendica/issues/7989
Types of hook-calls:
* `Hook::register()` just registers hooks, but doesn't add them to the current call
* `Hook::add()` just adds hook to the current call, but doesn't register them
Since we  want to call the db-definition hook just **once** during the install process, I switched from `Hook::register()` to `Hook:add()` and therefore removed the unregister call as well.
=> [advancedcontentfilter] Fix Hook-call during install 

markdown/README, markdown/lang/C/messages.po, markdown/markdown.php, markdown/templates/settings.tpl
This addon parses user input for Markdown content as well. This is highly experimental and could possibly lead to wrong parsing of BBCode elements. But since it can be enabled and disabled on a user level, users can test it out and report problems.
=> New Addon Markdown

markdown/markdown.php
I hope that these are now all elements that do contain content that could be falsely parsed by the Markdown parser.
=> Markdown: Protecting some more BBCode elements

showmore/showmore.php
The "show more" functionality doesn't make sense for screen readers. So we just override the visibility values for them.
=> Showmore: Ignore addon for screen readers

advancedcontentfilter/src/middlewares.php, advancedcontentfilter/src/routes.php, notifyall/NotifyAllEmail.php, securemail/SecureTestEmail.php
Except the "addon" files itself because there's (currently) a syntax which is used for loading
=> Add license headers
